services:
  - type: web
    name: xl-satu-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SPREADSHEET_ID
        value: 1Y6ex2HGUcGcDm18PMTPNKJlEZUrn-8YNU3hBg8o1XCo
      - key: PORT
        value: 10000
